title:              Flow Amonoy
email:              amonoyflow@gmail.com
description:        A Blog/Portfolio website.
author:             Flow Amonoy
baseurl:            ""
url:                "https://amonoyflow.github.io"
resume_url:         "https://drive.google.com/file/d/1IgnIxvOWR2I2VmHJMGFA827KJ9Dz_Osc/view"

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
