title:              Flow Amonoy
email:              amonoyflow@gmail.com
description:        A Blog/Portfolio website.
author:             Flow Amonoy
baseurl:            ""
url:                "https://amonoyflow.github.io"
resume_url:         "https://drive.google.com/open?id=1gjQbhEVI2N4dK3F6KN14SEOnBcva-RA2"

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
