title:              Flow Amonoy
email:              amonoyflow@gmail.com
description:        A Blog/Portfolio website.
author:             Flow Amonoy
baseurl:            ""
url:                "https://amonoyflow.github.io"
icon:               "../../../img/ic_florante.png"

google_analytics:   UA-165690186-1

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
